version: "3.6"
services:
  app:
    container_name: docker-watchmode-react
    image: docker-watchmode-react
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true